#!/usr/bin/php
<?php
/**
*   LSYNC. This module is responsible for user interaction and flow of control
*
* PHP Version 5
*
* @file     lxd-sync/main.php
* @category Sync two lxd servers
* @package  lxd-sync
* @author   Siddhant Rath <sid@tamu.edu>
* @license  http://www.apache.org/licenses/LICENSE-2.0  Apache License 2.0
*/

include_once('lxd_sync.php');
$shortopts  = "";
$longopts  = array(
    "sync-all::",
    "help::"
);
$options = getopt($shortopts, $longopts);
#var_dump($options);

if (isset($options["help"])) {
    help();
    exit(0);
}


$lxd_sync = new LXD_SYNC();
if (isset($options["sync-all"])) {
    $lxd_sync->startSync();
    exit(0);
}

printf('Please run with parameters'.PHP_EOL);
printf('use flags --help          : To get this help'.PHP_EOL);








function help() {
exec('clear');
printf ('lsync(1) LXD-SYNC'.PHP_EOL.PHP_EOL.PHP_EOL);
printf ('NAME'.PHP_EOL);
printf ('   lsync - sync containers frorm primary servers to a secondary server'.PHP_EOL.PHP_EOL.PHP_EOL);
printf ('AUTHOR'.PHP_EOL);
printf ('   Siddhant Rath | sid@tamu.edu | github.com/sidxz'.PHP_EOL.PHP_EOL.PHP_EOL);
printf('DESCRIPTION'.PHP_EOL);
printf('        --help          : Get this help message'.PHP_EOL);
printf('        --sync-all      : Sync all containers as per /etc/lxd_sync.conf file'.PHP_EOL);



}
?>

